language: go
go:
  - 1.11.x
cache:
  directories:
    - vendor
before_install:
  - wget -qO - http://packages.confluent.io/deb/3.2/archive.key | sudo apt-key add - # Use the confluent repository
  - sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/3.2 stable main"
  - sudo apt-get update -qq
  - sudo apt-get install -y librdkafka-dev librdkafka1
install:
  - curl https://raw.githubusercontent.com/golang/dep/v0.5.0/install.sh | sh
  - dep ensure -v
script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
  - golangci-lint run --disable=errcheck --enable=goimports,goconst,gocyclo
  - ./codecov.sh
after_success:
  - |
    test $TRAVIS_BRANCH = "master" && \
    test $TRAVIS_PULL_REQUEST = "false" && \
    curl -s --request POST \
      --header "content-type: application/json" \
      --header "accept: application/json" \
      --header "travis-api-version: 3" \
      --header "authorization: token $TRAVIS_API_TOKEN" \
      -d '{ "request": { "branch": "master", "message": "Automated Deployment. Commit ID: '$TRAVIS_COMMIT'." } }' \
      https://api.travis-ci.com/repo/serverless%2Fevent-gateway-connector-deploy/requests